
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kagan
 */
public class AddRecipeScreen extends javax.swing.JFrame {
     DefaultTableModel model;
     RecipesAddRemoveUpdate processes =new RecipesAddRemoveUpdate();
     ArrayList<Integer> ingredientIDlist = new ArrayList<Integer>();
     ArrayList<Float> ingredientMiktarlist = new ArrayList<Float>();




    /**
     * Creates new form AddRecipeScreen
     */
 
    public AddRecipeScreen() {
        initComponents();

        onaylaButton.setVisible(false);
        malzemeadiekleTF.setVisible(false);
        malzemebirimfiyatekleTF.setVisible(false);
        malzememiktariTF.setVisible(false);
        malzemebirimCB.setVisible(false);
        uyarilabel.setVisible(false);
        
        eklememiktarTF.setVisible(false);
        miktarButton.setVisible(false);
        miktarlabel.setVisible(false);
        malzemeCB.setVisible(false);
        
        model = (DefaultTableModel) malzemeTable.getModel();
        showIngredients();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarifekleButton = new javax.swing.JButton();
        tarifismiTF = new javax.swing.JTextField();
        tarifkategorisiCB = new javax.swing.JComboBox<>();
        tarifhazirlamasuresiTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarifmalzemeleriTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarifinhazirlanisiTA = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        malzemeTable = new javax.swing.JTable();
        malzemeekleButton = new javax.swing.JButton();
        malzemeadiekleTF = new javax.swing.JTextField();
        malzememiktariTF = new javax.swing.JTextField();
        malzemebirimfiyatekleTF = new javax.swing.JTextField();
        malzemebirimCB = new javax.swing.JComboBox<>();
        onaylaButton = new javax.swing.JButton();
        miktarlabel = new javax.swing.JLabel();
        eklememiktarTF = new javax.swing.JTextField();
        miktarButton = new javax.swing.JButton();
        malzemeCB = new javax.swing.JComboBox<>();
        uyarilabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tarif Ekle");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarif İsmi:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tarif Kategorisi:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarif Hazırlanma Süresi:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tarif Malzemeleri:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tarifin Hazırlanışı:");

        tarifekleButton.setBackground(new java.awt.Color(51, 204, 255));
        tarifekleButton.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        tarifekleButton.setForeground(new java.awt.Color(0, 204, 0));
        tarifekleButton.setText("➕");
        tarifekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifekleButtonActionPerformed(evt);
            }
        });

        tarifismiTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        tarifkategorisiCB.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifkategorisiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Ana Yemekler", "Tatlılar", "İçecekler", "Ara Sıcaklar", "Salatalar" }));

        tarifhazirlamasuresiTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifhazirlamasuresiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifhazirlamasuresiTFActionPerformed(evt);
            }
        });

        tarifmalzemeleriTA.setColumns(20);
        tarifmalzemeleriTA.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifmalzemeleriTA.setRows(5);
        jScrollPane1.setViewportView(tarifmalzemeleriTA);

        tarifinhazirlanisiTA.setColumns(20);
        tarifinhazirlanisiTA.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifinhazirlanisiTA.setRows(5);
        jScrollPane2.setViewportView(tarifinhazirlanisiTA);

        backButton.setBackground(new java.awt.Color(51, 204, 255));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        backButton.setText("⬅");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        malzemeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme Adı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        malzemeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzemeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(malzemeTable);
        if (malzemeTable.getColumnModel().getColumnCount() > 0) {
            malzemeTable.getColumnModel().getColumn(0).setResizable(false);
        }

        malzemeekleButton.setBackground(new java.awt.Color(51, 204, 255));
        malzemeekleButton.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        malzemeekleButton.setText("+");
        malzemeekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemeekleButtonActionPerformed(evt);
            }
        });

        malzemeadiekleTF.setForeground(new java.awt.Color(204, 204, 204));
        malzemeadiekleTF.setText("Malzeme adı");
        malzemeadiekleTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzemeadiekleTFMouseClicked(evt);
            }
        });
        malzemeadiekleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemeadiekleTFActionPerformed(evt);
            }
        });

        malzememiktariTF.setForeground(new java.awt.Color(204, 204, 204));
        malzememiktariTF.setText("Malzeme miktarı");
        malzememiktariTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzememiktariTFMouseClicked(evt);
            }
        });
        malzememiktariTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzememiktariTFActionPerformed(evt);
            }
        });

        malzemebirimfiyatekleTF.setForeground(new java.awt.Color(204, 204, 204));
        malzemebirimfiyatekleTF.setText("Birim fiyat");
        malzemebirimfiyatekleTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzemebirimfiyatekleTFMouseClicked(evt);
            }
        });

        malzemebirimCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "kg", "adet", "litre" }));

        onaylaButton.setBackground(new java.awt.Color(51, 204, 255));
        onaylaButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        onaylaButton.setText("✔");
        onaylaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaButtonActionPerformed(evt);
            }
        });

        miktarlabel.setText("Miktar:");

        miktarButton.setBackground(new java.awt.Color(51, 204, 255));
        miktarButton.setText("✔");
        miktarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miktarButtonActionPerformed(evt);
            }
        });

        malzemeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "litre", "adet" }));

        uyarilabel.setForeground(new java.awt.Color(255, 51, 51));
        uyarilabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uyarilabel.setText("Bu tarif zaten var");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(745, 745, 745)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(40, 40, 40)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(miktarlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eklememiktarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(malzemeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(miktarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(malzemeekleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(malzemeadiekleTF)
                                    .addComponent(malzememiktariTF, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(malzemebirimCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(malzemebirimfiyatekleTF))
                                .addGap(18, 18, 18)
                                .addComponent(onaylaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(tarifhazirlamasuresiTF)
                            .addComponent(tarifkategorisiCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarifismiTF)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uyarilabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarifekleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(759, 759, 759))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarifismiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarifkategorisiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarifhazirlamasuresiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(miktarlabel)
                                    .addComponent(eklememiktarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(miktarButton)
                                    .addComponent(malzemeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(malzemeekleButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(malzemeadiekleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(malzememiktariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(onaylaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(malzemebirimCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(malzemebirimfiyatekleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(uyarilabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarifekleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarifekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifekleButtonActionPerformed
        // TODO add your handling code here:
        
        String ad = tarifismiTF.getText();
        String kategori = (String) tarifkategorisiCB.getSelectedItem();
        int sure = Integer.parseInt(tarifhazirlamasuresiTF.getText()); 
        String talimatlar = tarifinhazirlanisiTA.getText();
        String fotoUrl = "/Users/kagan/Desktop/projeyemek/"+ad.toLowerCase()+".jpg";
        
        if(processes.isRecipeExists(ad)){
            uyarilabel.setVisible(true);
        
        }else{
              processes.AddRecipes(ad, kategori, sure, talimatlar,fotoUrl);
              
              int i =0;
              while(i<ingredientIDlist.size()){
                              processes.AddRecipeIngredients(processes.GetRecipeDetails(ad).getId(),ingredientIDlist.get(i) ,ingredientMiktarlist.get(i));
              }

        dispose();
        
        }
        
        
    }//GEN-LAST:event_tarifekleButtonActionPerformed

    private void tarifhazirlamasuresiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifhazirlamasuresiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifhazirlamasuresiTFActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void malzemeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzemeTableMouseClicked
        // TODO add your handling code here:

        //Malzemeyi miktarıyla birlikte kaydettiğimiz kısım
        eklememiktarTF.setVisible(true);
        miktarButton.setVisible(true);
        miktarlabel.setVisible(true);
        malzemeCB.setVisible(true);
        int selectedrow = malzemeTable.getSelectedRow();
        String ad = model.getValueAt(selectedrow, 0).toString();
        malzemeCB.setSelectedItem(processes.GetIngredientDetails(ad).getMalzemebirim());

    }//GEN-LAST:event_malzemeTableMouseClicked

    private void malzemeadiekleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemeadiekleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malzemeadiekleTFActionPerformed

    private void malzememiktariTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzememiktariTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malzememiktariTFActionPerformed

    private void malzemeekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemeekleButtonActionPerformed
        // TODO add your handling code here:
        
        onaylaButton.setVisible(true);
        malzemeadiekleTF.setVisible(true);
        malzemebirimfiyatekleTF.setVisible(true);
        malzememiktariTF.setVisible(true);
        malzemebirimCB.setVisible(true);
        malzemeadiekleTF.setText("Malzeme adı");
        malzemebirimfiyatekleTF.setText("Birim fiyat");
        malzememiktariTF.setText("Malzeme miktarı");
        malzemebirimCB.setVisible(true);
        
        malzemeadiekleTF.setForeground(Color.LIGHT_GRAY);
        malzememiktariTF.setForeground(Color.LIGHT_GRAY);
        malzemebirimfiyatekleTF.setForeground(Color.LIGHT_GRAY);

        
    }//GEN-LAST:event_malzemeekleButtonActionPerformed

    private void malzemeadiekleTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzemeadiekleTFMouseClicked
        // TODO add your handling code here:
        if(malzemeadiekleTF.getText().equals("Malzeme adı"))
        malzemeadiekleTF.setText("");
        malzemeadiekleTF.setForeground(Color.BLACK);
    }//GEN-LAST:event_malzemeadiekleTFMouseClicked

    private void malzememiktariTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzememiktariTFMouseClicked
        // TODO add your handling code here:
        if(malzememiktariTF.getText().equals("Malzeme miktarı"))
        malzememiktariTF.setText("");
        malzememiktariTF.setForeground(Color.BLACK);
    }//GEN-LAST:event_malzememiktariTFMouseClicked

    private void malzemebirimfiyatekleTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzemebirimfiyatekleTFMouseClicked
        // TODO add your handling code here:
        if(malzemebirimfiyatekleTF.getText().equals("Birim fiyat"))
        malzemebirimfiyatekleTF.setText("");
        malzemebirimfiyatekleTF.setForeground(Color.BLACK);
    }//GEN-LAST:event_malzemebirimfiyatekleTFMouseClicked

    private void onaylaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaButtonActionPerformed
        // TODO add your handling code here:
        
        String ad = malzemeadiekleTF.getText();
        String malzemebirim = (String) malzemebirimCB.getSelectedItem();
        int fiyat = Integer.parseInt(malzemebirimfiyatekleTF.getText()); 
        String miktar = malzememiktariTF.getText();
        
        if(processes.isIngredientExists(ad)){
        
        
          }else{
              processes.AddIngredients(ad, malzemebirim,fiyat , miktar);     
          }
       
    }//GEN-LAST:event_onaylaButtonActionPerformed

    private void miktarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miktarButtonActionPerformed
        // TODO add your handling code here:


        eklememiktarTF.setVisible(false);
        miktarButton.setVisible(false);
        miktarlabel.setVisible(false);
        malzemeCB.setVisible(false);
        
        
        
        
       int selectedrow = malzemeTable.getSelectedRow();
       String ad = model.getValueAt(selectedrow, 0).toString();
                     
                     
       ingredientIDlist.add(processes.GetIngredientDetails(ad).getId());
       ingredientMiktarlist.add(Float.parseFloat(eklememiktarTF.getText()));
                     
            if(tarifmalzemeleriTA.getText().equals("")){
            
                        tarifmalzemeleriTA.setText(tarifmalzemeleriTA.getText()+ad);
            }else{
            
                        tarifmalzemeleriTA.setText(tarifmalzemeleriTA.getText()+","+ad);

            
            }

 
    }//GEN-LAST:event_miktarButtonActionPerformed

   
    
        public void showIngredients(){
    model.setRowCount(0);
    
        ArrayList<Ingredients> ingredients = new ArrayList<Ingredients>();
        
        ingredients = processes.getIngredients();
        
        if(ingredients != null){
        
            for(Ingredients ingredient : ingredients){
            
                Object[] next = {ingredient.getAd()};
                
                model.addRow(next);
                
            }
     
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecipeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField eklememiktarTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> malzemeCB;
    private javax.swing.JTable malzemeTable;
    private javax.swing.JTextField malzemeadiekleTF;
    private javax.swing.JComboBox<String> malzemebirimCB;
    private javax.swing.JTextField malzemebirimfiyatekleTF;
    private javax.swing.JButton malzemeekleButton;
    private javax.swing.JTextField malzememiktariTF;
    private javax.swing.JButton miktarButton;
    private javax.swing.JLabel miktarlabel;
    private javax.swing.JButton onaylaButton;
    private javax.swing.JButton tarifekleButton;
    private javax.swing.JTextField tarifhazirlamasuresiTF;
    private javax.swing.JTextArea tarifinhazirlanisiTA;
    private javax.swing.JTextField tarifismiTF;
    private javax.swing.JComboBox<String> tarifkategorisiCB;
    private javax.swing.JTextArea tarifmalzemeleriTA;
    private javax.swing.JLabel uyarilabel;
    // End of variables declaration//GEN-END:variables
}
