
import java.awt.Color;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import javax.swing.JTable;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kagan
 */
public class HomeScreen extends javax.swing.JFrame {   
     DefaultTableModel model;
     DefaultTableModel model2;
     DefaultTableModel model3;
     ArrayList<Integer> ingredientlist = new ArrayList<Integer>();
     ArrayList<Integer> recipeList = new ArrayList<Integer>();
     ArrayList<Recipes> sendrecipeList = new ArrayList<Recipes>();
     RecipesAddRemoveUpdate processes =new RecipesAddRemoveUpdate();
    
    /**
     * 
     *
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
        model = (DefaultTableModel) tarifTable.getModel();
        model2 = (DefaultTableModel) malzemeTable.getModel();
        model3=(DefaultTableModel) aramaTable.getModel();
        showRecipes();
        showIngredients();
        
        aramaTable.setDefaultRenderer(Object.class, new CustomRenderer());
        
        startRecipeCheckTimer();
    }
    
        class CustomRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // İlk sütundaki değeri al
            String firstColumnValue = table.getValueAt(row, 1).toString();

            // Koşula göre tüm satırın yazı rengini değiştir
            if (firstColumnValue.equals("0.0")) { // Koşulu kendine göre ayarla
                c.setForeground(Color.GREEN.darker());  // Yazı rengini yeşil yap
            } else {
                c.setForeground(Color.RED);    // Yazı rengini kırmızı yap
            }

            return c;
        }
    }
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarifTable = new javax.swing.JTable();
        tarifekleButton = new javax.swing.JButton();
        tarifguncelleButton = new javax.swing.JButton();
        tarifsilButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        aramaTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        yenileButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        aramaTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        malzemeTable = new javax.swing.JTable();
        malzemeklemeTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        araButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        siralamaCB = new javax.swing.JComboBox<>();
        malzemesayisiCB = new javax.swing.JComboBox<>();
        maliyetaraligiCB = new javax.swing.JComboBox<>();
        kategoriCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tarif Listesi");

        tarifTable.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Hazırlama Süresi", "Maliyet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tarifTable.setRowHeight(40);
        tarifTable.setRowMargin(5);
        tarifTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarifTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tarifTable);
        if (tarifTable.getColumnModel().getColumnCount() > 0) {
            tarifTable.getColumnModel().getColumn(0).setResizable(false);
            tarifTable.getColumnModel().getColumn(1).setResizable(false);
            tarifTable.getColumnModel().getColumn(2).setResizable(false);
        }

        tarifekleButton.setText("Tarif Ekle");
        tarifekleButton.setBorder(null);
        tarifekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifekleButtonActionPerformed(evt);
            }
        });

        tarifguncelleButton.setText("Tarif Güncelle");
        tarifguncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifguncelleButtonActionPerformed(evt);
            }
        });

        tarifsilButton.setText("Tarif Sil");
        tarifsilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifsilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tarifekleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tarifguncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(tarifsilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tarifekleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarifguncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(tarifsilButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 51, 255));

        aramaTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        aramaTF.setForeground(new java.awt.Color(204, 204, 204));
        aramaTF.setText("Tarif adı girerek arama yap.");
        aramaTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aramaTFMouseClicked(evt);
            }
        });
        aramaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaTFActionPerformed(evt);
            }
        });
        aramaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aramaTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaTFKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(aramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator1)
                .addGap(285, 285, 285))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(aramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Arama Sonuçları");

        yenileButton.setText("Yenile");
        yenileButton.setToolTipText("Uygulamayı yeniden başlatır.");
        yenileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButtonActionPerformed(evt);
            }
        });

        aramaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarif Adı", "Eksik Malzemelerin Maliyeti", "Uyuşma Yüzdesi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(aramaTable);
        if (aramaTable.getColumnModel().getColumnCount() > 0) {
            aramaTable.getColumnModel().getColumn(0).setResizable(false);
            aramaTable.getColumnModel().getColumn(1).setResizable(false);
            aramaTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 150, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(yenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel4.setBackground(new java.awt.Color(153, 51, 255));

        malzemeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme Adı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        malzemeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzemeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(malzemeTable);
        if (malzemeTable.getColumnModel().getColumnCount() > 0) {
            malzemeTable.getColumnModel().getColumn(0).setResizable(false);
        }

        malzemeklemeTF.setEditable(false);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Malzeme seçerek arama yap");

        clearButton.setText("✖");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(malzemeklemeTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(malzemeklemeTF)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 51, 255));

        araButton.setText("Ara");
        araButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sıralama:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Malzeme Sayısı:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Maliyet Aralığı:");

        siralamaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Hızlı", "Yavaş", "Pahalı", "Ucuz" }));
        siralamaCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siralamaCBMouseClicked(evt);
            }
        });

        malzemesayisiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "0-3", "3-6", "6-9", "+9" }));

        maliyetaraligiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "50₺ altı", "50₺-100₺", "100₺-200₺", "200₺ üstü" }));

        kategoriCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Ana Yemekler", "Tatlılar", "İçecekler", "Ara Sıcaklar", "Salatalar" }));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kategori:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(araButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(259, 259, 259)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategoriCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(malzemesayisiCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 136, Short.MAX_VALUE)
                        .addComponent(siralamaCB, 0, 136, Short.MAX_VALUE)
                        .addComponent(maliyetaraligiCB, 0, 136, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(siralamaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malzemesayisiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maliyetaraligiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(araButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarifguncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifguncelleButtonActionPerformed
        // TODO add your handling code here:
        UpdateRecipeScreen updateRecipeScreen = new UpdateRecipeScreen();
        updateRecipeScreen.setVisible(true);
    }//GEN-LAST:event_tarifguncelleButtonActionPerformed

    private void araButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araButtonActionPerformed
        // TODO add your handling code here:
       sendrecipeList.clear();
       //Tariflerin idsinin bir arraylistte tutulması
       recipeList = processes.getRecipesWithAllIngredients(ingredientlist);
       
       for(Integer recipeID:recipeList){
       sendrecipeList.add(processes.GetRecipeDetailsWithID(recipeID));
       }
     
         showNameSearchResult();
 
    }//GEN-LAST:event_araButtonActionPerformed

    private void aramaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aramaTFActionPerformed

    private void tarifekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifekleButtonActionPerformed
        // TODO add your handling code here:
        AddRecipeScreen addRecipeScreen = new AddRecipeScreen();
        addRecipeScreen.setVisible(true);
    }//GEN-LAST:event_tarifekleButtonActionPerformed

    private void tarifsilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifsilButtonActionPerformed
        // TODO add your handling code here:
        RemoveRecipeScreen removeRecipeScreen = new RemoveRecipeScreen();
        removeRecipeScreen.setVisible(true);
    }//GEN-LAST:event_tarifsilButtonActionPerformed

    private void yenileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButtonActionPerformed
        // TODO add your handling code here
    showRecipes();
    kategoriCB.setSelectedIndex(0);
    siralamaCB.setSelectedIndex(0);
    maliyetaraligiCB.setSelectedIndex(0);
    malzemesayisiCB.setSelectedIndex(0);
    aramaTF.setText("Tarif adı girerek arama yap.");
    aramaTF.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_yenileButtonActionPerformed

    private void tarifTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifTableMouseClicked
        // TODO add your handling code here:
        
       // Tarif detayları sayfasına gidilen kısım
       
            int selectedrow = tarifTable.getSelectedRow();
            String ad = model.getValueAt(selectedrow, 0).toString();
 
            Recipes recipe =new Recipes(); 
            recipe=processes.GetRecipeDetails(ad);
            
            ArrayList<Ingredients> ingredientlist = new ArrayList<Ingredients>();
            ingredientlist = processes.getIngredientsByRecipeName(recipe.getAd());
        
            DetailsRecipeScreen detailsRecipeScreen = new DetailsRecipeScreen(recipe.getAd(), recipe.getKategori(), recipe.getSure(), recipe.getTalimatlar(),recipe.getFotoUrl(),ingredientlist);
            detailsRecipeScreen.setVisible(true);
    }//GEN-LAST:event_tarifTableMouseClicked

    private void aramaTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aramaTFMouseClicked
        // TODO add your handling code here:
        if(aramaTF.getText().equals("Tarif adı girerek arama yap."))
        aramaTF.setText("");
    }//GEN-LAST:event_aramaTFMouseClicked

    private void aramaTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaTFKeyPressed
        // TODO add your handling code here:
        aramaTF.setForeground(Color.BLACK);
    }//GEN-LAST:event_aramaTFKeyPressed

    private void siralamaCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siralamaCBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_siralamaCBMouseClicked

    private void malzemeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzemeTableMouseClicked
        // TODO add your handling code here:
        
        //Malzeme adlarına tıklayarak seçtiğimiz kısım
        
            int selectedrow = malzemeTable.getSelectedRow();
            String ad = model2.getValueAt(selectedrow, 0).toString();
            
            if(malzemeklemeTF.getText().equals("")){
                        malzemeklemeTF.setText(malzemeklemeTF.getText()+ad);
            }else{
                        malzemeklemeTF.setText(malzemeklemeTF.getText()+","+ad);
            }
            
            ingredientlist.add(processes.GetIngredientDetails(ad).getId());
    }//GEN-LAST:event_malzemeTableMouseClicked

    private void aramaTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaTFKeyReleased
        // TODO add your handling code here:
        showNameSearchResult();
    }//GEN-LAST:event_aramaTFKeyReleased

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        malzemeklemeTF.setText("");
        ingredientlist.clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showRecipes(){      //model e tüm tarifleri gönderdiğimiz kısım
    model.setRowCount(0);
    
        ArrayList<Recipes> recipes = new ArrayList<Recipes>();
        recipes = processes.getRecipes();
        
        if(recipes != null){
            for(Recipes recipe : recipes){
                Object[] next = {recipe.getAd(),recipe.getSure(),recipe.getMaliyet()};
                model.addRow(next);
            }
        }
    }
    
    public void showIngredients(){      //model2 ye tüm malzemeleri gönderdiğimiz kısım
    model2.setRowCount(0);
    
        ArrayList<Ingredients> ingredients = new ArrayList<Ingredients>();
        ingredients = processes.getIngredients();
        
        if(ingredients != null){
            for(Ingredients ingredient : ingredients){
                Object[] next = {ingredient.getAd()};
                model2.addRow(next);
            }
        }
    }
            
            
    public void showIngredientSearchResult(){
            
            model3.setRowCount(0);
            
            ArrayList<Recipes> recipes = new ArrayList<Recipes>();
            
            for(Integer recipe:recipeList){
            
                recipes.add(processes.GetRecipeDetailsWithID(recipe));
            
            }
            
            
       if(recipes != null){
        
            for(Recipes recipe : recipes){
            
                Object[] next = {recipe.getAd()};
                
                model3.addRow(next);
                
            }
        }
            
            
            
    }
    
    
    public void showNameSearchResult(){     //Sonuç kısmını yazdırdığımız kısım
        model3.setRowCount(0);
    
       if(sendrecipeList.isEmpty()){
         ArrayList<Recipes> recipes = new ArrayList<Recipes>();
         recipes = processes.SearchWithName(aramaTF.getText(),
                                           siralamaCB.getSelectedItem().toString(), 
                                           malzemesayisiCB.getSelectedItem().toString(),
                                           maliyetaraligiCB.getSelectedItem().toString(),
                                           kategoriCB.getSelectedItem().toString());
        
         if(recipes != null){
             for(Recipes recipe : recipes){
                 Object[] next = {recipe.getAd(), processes.getEksikMalzemeMaliyeti(recipe.getAd())};
                 model3.addRow(next);
            }
        }
    
    
    
            }else{
        
                sendrecipeList = processes.SearchWithIngredient(sendrecipeList,
                                           siralamaCB.getSelectedItem().toString(), 
                                           malzemesayisiCB.getSelectedItem().toString(),
                                           maliyetaraligiCB.getSelectedItem().toString(),
                                           kategoriCB.getSelectedItem().toString());
          
          
                 if(sendrecipeList != null){
                      for(Recipes recipe: sendrecipeList){
                          recipe.setUyum(processes.calculateMatchingPercentage(recipe, ingredientlist));
                          Object[] next = {recipe.getAd(), processes.getEksikMalzemeMaliyeti(recipe.getAd()), recipe.getUyum()};
                          model3.addRow(next);
              }
          }
       }
  }
 
    private void startRecipeCheckTimer() {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                // Tariflerin boş olup olmadığını kontrol et
                if (aramaTF.getText().equals("")) {
                          aramaTF.setText("Tarif adı girerek arama yap.");
                          aramaTF.setForeground(Color.LIGHT_GRAY);
                } 
            }
        }, 0, 15000); // 0 gecikme, 10 saniyede bir kontrol
    }
    


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton araButton;
    private javax.swing.JTextField aramaTF;
    private javax.swing.JTable aramaTable;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> kategoriCB;
    private javax.swing.JComboBox<String> maliyetaraligiCB;
    private javax.swing.JTable malzemeTable;
    private javax.swing.JTextField malzemeklemeTF;
    private javax.swing.JComboBox<String> malzemesayisiCB;
    private javax.swing.JComboBox<String> siralamaCB;
    private javax.swing.JTable tarifTable;
    private javax.swing.JButton tarifekleButton;
    private javax.swing.JButton tarifguncelleButton;
    private javax.swing.JButton tarifsilButton;
    private javax.swing.JButton yenileButton;
    // End of variables declaration//GEN-END:variables
}
