
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kagan
 */
public class UpdateRecipeScreen extends javax.swing.JFrame {
    
        RecipesAddRemoveUpdate processes = new RecipesAddRemoveUpdate();
        DefaultTableModel model ;
    /**
     * Creates new form UpdateRecipeScreen
     */
    public UpdateRecipeScreen() {
            
            
        initComponents();
        model = (DefaultTableModel) tariftable.getModel();
        showRecipes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        tarifiguncelleButton = new javax.swing.JButton();
        tarifismiTF = new javax.swing.JTextField();
        tarifkategorisiCB = new javax.swing.JComboBox<>();
        tarifhazirlamasuresiTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarifmalzemeleriTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarifinhazirlanisiTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tariftable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(51, 204, 255));

        jLabel67.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Tarif Güncelle");

        jLabel68.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Tarif İsmi:");

        jLabel69.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Tarif Kategorisi:");

        jLabel70.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Tarif Hazırlanma Süresi:");

        jLabel71.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Tarif Malzemeleri:");

        jLabel72.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Tarifin Hazırlanışı:");

        tarifiguncelleButton.setBackground(new java.awt.Color(51, 204, 255));
        tarifiguncelleButton.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        tarifiguncelleButton.setText("🔁");
        tarifiguncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifiguncelleButtonActionPerformed(evt);
            }
        });

        tarifismiTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifismiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifismiTFActionPerformed(evt);
            }
        });

        tarifkategorisiCB.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifkategorisiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Ana Yemek", "Tatlı", "İçecek", "Ara Sıcak", "Salata" }));

        tarifhazirlamasuresiTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        tarifmalzemeleriTA.setColumns(20);
        tarifmalzemeleriTA.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifmalzemeleriTA.setRows(5);
        jScrollPane1.setViewportView(tarifmalzemeleriTA);

        tarifinhazirlanisiTA.setEditable(false);
        tarifinhazirlanisiTA.setColumns(20);
        tarifinhazirlanisiTA.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tarifinhazirlanisiTA.setRows(5);
        jScrollPane2.setViewportView(tarifinhazirlanisiTA);

        tariftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tarif Adı", "Kategori", "Hazırlama Süresi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tariftable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tariftableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tariftable);
        if (tariftable.getColumnModel().getColumnCount() > 0) {
            tariftable.getColumnModel().getColumn(0).setResizable(false);
            tariftable.getColumnModel().getColumn(1).setResizable(false);
            tariftable.getColumnModel().getColumn(2).setResizable(false);
            tariftable.getColumnModel().getColumn(3).setResizable(false);
        }

        backButton.setBackground(new java.awt.Color(51, 204, 255));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        backButton.setText("⬅");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jLabel69))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarifkategorisiCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tarifhazirlamasuresiTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tarifismiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(677, 677, 677)
                        .addComponent(tarifiguncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(707, 707, 707)
                        .addComponent(jLabel67)))
                .addContainerGap(710, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel68)
                            .addComponent(tarifismiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarifkategorisiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarifhazirlamasuresiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarifiguncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarifiguncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifiguncelleButtonActionPerformed
        // TODO add your handling code here:
                String ad = tarifismiTF.getText();
                String kategori = (String) tarifkategorisiCB.getSelectedItem();
                int sure = Integer.parseInt(tarifhazirlamasuresiTF.getText()); 
                String talimatlar = tarifinhazirlanisiTA.getText();
        
        
                int selectedrow = tariftable.getSelectedRow();
                
                if(selectedrow == -1){
                
                    if(model.getRowCount() == 0){
                    
                    }else{
                    
                    
                    
                    
                    }
                    
                
                
                
                }else{
                
                int id = (int)model.getValueAt(selectedrow,0);
                    
                    processes.UpdateRecipes(id, ad, kategori, sure, talimatlar);
                    showRecipes();
                    
                }

                
                
                
                
                
        dispose();
                
                
                

    }//GEN-LAST:event_tarifiguncelleButtonActionPerformed

    private void tarifismiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifismiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifismiTFActionPerformed

    private void tariftableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tariftableMouseClicked
        // TODO add your handling code here:
        ArrayList<Ingredients> ingredients = new ArrayList<Ingredients>();
        
        int selectedrow = tariftable.getSelectedRow();
        Recipes recipe = new Recipes();
        recipe = processes.GetRecipeDetails(model.getValueAt(selectedrow,1).toString());
        int sure2 =recipe.getSure();
        
        ingredients = processes.getIngredientsByRecipeName(recipe.getAd());
                String malzemeler = "";
        for(Ingredients ingredient:ingredients){
        
            malzemeler = malzemeler + ingredient.getAd()+"\n";
        
        }

        
        tarifismiTF.setText(recipe.getAd());
        tarifkategorisiCB.setEditable(true);
        tarifkategorisiCB.setSelectedItem(recipe.getKategori());
        tarifmalzemeleriTA.setText(malzemeler);
        tarifhazirlamasuresiTF.setText(Integer.toString(sure2));
        tarifinhazirlanisiTA.setText(recipe.getTalimatlar());

        
    }//GEN-LAST:event_tariftableMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
           public void showRecipes(){
    model.setRowCount(0);
    
        ArrayList<Recipes> recipes = new ArrayList<Recipes>();
        
        recipes = processes.getRecipes();
        
        if(recipes != null){
        
            for(Recipes recipe : recipes){
            
                Object[] next = {recipe.getId(),recipe.getAd(),recipe.getKategori(),recipe.getSure(),recipe.getTalimatlar()};
                
                model.addRow(next);
                
            }
            
            
            
        
        
        }
    
    
    
    
    
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRecipeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField tarifhazirlamasuresiTF;
    private javax.swing.JButton tarifiguncelleButton;
    private javax.swing.JTextArea tarifinhazirlanisiTA;
    private javax.swing.JTextField tarifismiTF;
    private javax.swing.JComboBox<String> tarifkategorisiCB;
    private javax.swing.JTextArea tarifmalzemeleriTA;
    private javax.swing.JTable tariftable;
    // End of variables declaration//GEN-END:variables
}
